 
/**
 * @file 98_WorkflowLogger.gs
 * @description Enhanced logging with human-readable durations, verbose narrations,
 * and Data Integrity scanning. Respects the global notification toggle.
 * Updated to use bulletproof, high-reliability proxy-safe error icons and titles.
 */

/**
 * Scans key columns for "Broken" or "⚠️" flags generated by array formulas.
 * @param {GoogleAppsScript.Spreadsheet.Spreadsheet} ss The target spreadsheet.
 * @param {object} config The workflow configuration.
 */
function performIntegrityCheck(ss, config) {
  workflowLog("Scanning for Data Integrity issues...", "INTEGRITY_CHECK", null, ss);

  const checks = [
    { sheet: "PDUData", cols: ["AT", "AU", "AW"] },
    { sheet: "CablingData", cols: ["B", "C", "D", "H", "I", "M"] }
  ];

  let issues = [];

  checks.forEach(check => {
    const sheet = ss.getSheetByName(check.sheet);
    if (!sheet) return;

    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return;

    check.cols.forEach(colLetter => {
      const range = sheet.getRange(`${colLetter}2:${colLetter}${lastRow}`);
      const data = range.getValues();
      const brokenCount = data.filter(row => {
        const val = String(row[0]);
        return val.includes("Broken") || val.includes("⚠️");
      }).length;

      if (brokenCount > 0) {
        issues.push(`${brokenCount} issues in ${check.sheet} (${colLetter})`);
      }
    });
  });

  if (issues.length > 0) {
    const alertMsg = "Integrity Check Failed:\n" + issues.join("\n");
    workflowLog(alertMsg, "INTEGRITY_CHECK", null, ss);
    sendErrorNotificationToChat(alertMsg, "INTEGRITY_CHECK", config);
  } else {
    workflowLog("Integrity Check Passed: No broken data found.", "INTEGRITY_CHECK", null, ss);
  }
}

/**
 * Appends a log entry to the "WorkflowLogs" sheet with human-readable duration.
 * @param {string} message The message to log.
 * @param {string} step The current workflow step name.
 * @param {number} [startTime] Optional millisecond timestamp to calculate duration.
 * @param {GoogleAppsScript.Spreadsheet.Spreadsheet} [ss] Optional spreadsheet object.
 */
function workflowLog(message, step = "GENERAL", startTime, ss) {
  try {
    let targetSS;
    try {
      targetSS = ss || SpreadsheetApp.getActiveSpreadsheet();
      if (!targetSS || targetSS.getName() === "Untitled spreadsheet") throw new Error();
    } catch (e) {
      targetSS = SpreadsheetApp.openById(FTR_SHEET_ID_PROD);
    }

    let logSheet = targetSS.getSheetByName("WorkflowLogs");

    if (!logSheet) {
      logSheet = targetSS.insertSheet("WorkflowLogs");
      logSheet.appendRow(["Timestamp", "Step", "Message", "Duration"]);
      logSheet.getRange(1, 1, 1, 4).setFontWeight("bold").setBackground("#efefef");
      logSheet.setFrozenRows(1);
    }

    let durationFormatted = "";
    if (startTime) {
      const seconds = (new Date().getTime() - startTime) / 1000;
      durationFormatted = formatDuration_(seconds);
    }

    const ts = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), "HH:mm:ss");
    logSheet.appendRow([ts, step, message, durationFormatted]);

    Logger.log(`[${step}] ${message} ${durationFormatted ? "(" + durationFormatted + ")" : ""}`);

  } catch (e) {
    Logger.log(`Logging Error: ${e.message} | Original Msg: [${step}] ${message}`);
  }
}

/**
 * Converts seconds into a human-readable string (e.g., 3m 22s).
 * @private
 */
function formatDuration_(seconds) {
  if (!seconds || seconds < 0.1) return "";
  if (seconds < 60) return seconds.toFixed(1) + "s";

  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}m ${secs}s`;
}

/**
 * Clears logs in the target spreadsheet.
 */
function clearWorkflowLogs(ss) {
  try {
    const targetSS = ss || SpreadsheetApp.getActiveSpreadsheet();
    const logSheet = targetSS.getSheetByName("WorkflowLogs");
    if (logSheet && logSheet.getLastRow() > 1) {
      logSheet.getRange(2, 1, logSheet.getLastRow() - 1, 4).clearContent();
    }
  } catch (e) {
    Logger.log(`Clear Logs Error: ${e.message}`);
  }
}

/**
 * Completely clears all script properties associated with workflow progress.
 */
function clearWorkflowState() {
  const props = PropertiesService.getScriptProperties();
  const keysToWipe = [
    'STEP_INDEX', 'WF_CONFIG', 'IMPORT_STAGE', 'RELINK_CHART_INDEX',
    'PDU_DATA_ROW_INDEX', 'PDU_FORMULA_ROW_INDEX', 'RACK_DATA_ROW_INDEX',
    'RACK_FORMULA_ROW_INDEX', 'UNIQUE_RACK_COUNT', 'MEM_RACK', 'MEM_PDU'
  ];
  keysToWipe.forEach(key => props.deleteProperty(key));
  Logger.log("Workflow progress properties have been cleared.");
}

/**
 * Checks if a previous run is in progress and prompts the user.
 */
function handleWorkflowRecovery() {
  const props = PropertiesService.getScriptProperties();
  const stepIndex = props.getProperty('STEP_INDEX');
  const importStage = props.getProperty('IMPORT_STAGE');

  if (stepIndex !== null || importStage !== null) {
    const ui = SpreadsheetApp.getUi();
    const result = ui.alert(
      'Workflow Recovery Detected',
      'The last run appears to have crashed or paused mid-process.\n\n' +
      'Would you like to RESUME where it left off?\n' +
      '(Select "No" to start a completely CLEAN run)',
      ui.ButtonSet.YES_NO
    );

    if (result == ui.Button.NO) {
      clearWorkflowState();
      clearWorkflowLogs();
      return false;
    }
    return true;
  }
  return false;
}

/**
 * Specifically logs fatal errors that occur before the target environment is ready.
 */
function reportFatalError(errorMessage, context = "INITIALIZATION") {
  const prodSS = SpreadsheetApp.openById(FTR_SHEET_ID_PROD);
  workflowLog(`⛔ FATAL ERROR: ${errorMessage}`, context, null, prodSS);

  if (typeof ENABLE_CHAT_NOTIFICATIONS !== 'undefined' && ENABLE_CHAT_NOTIFICATIONS) {
    sendErrorNotificationToChat(errorMessage, context, { sheetId: FTR_SHEET_ID_PROD });
  }
}

/**
 * Sends a failure alert card to Google Chat, respecting the global toggle.
 * Uses high-reliability cross icon and native emoji header titles.
 */
function sendErrorNotificationToChat(errorMessage, step, config) {
  if (typeof ENABLE_CHAT_NOTIFICATIONS !== 'undefined' && !ENABLE_CHAT_NOTIFICATIONS) {
    Logger.log("Chat notifications are disabled. Skipping error alert.");
    return;
  }

  const sheetId = config ? config.sheetId : SpreadsheetApp.getActiveSpreadsheet().getId();
  const sheetUrl = `https://docs.google.com/spreadsheets/d/${sheetId}`;

  // High-reliability red cross icon hosted on Wikimedia CDN (proxy-safe PNG)
  const errorIconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flat_cross_icon.svg/240px-Flat_cross_icon.svg.png";

  const card = {
    'cardsV2': [{
      'cardId': 'errorCard',
      'card': {
        'header': {
          'title': '🔴 FTR ALERT: Workflow Failure',
          'subtitle': `Step: ${step}`,
          'imageUrl': errorIconUrl,
          'imageType': 'CIRCLE'
        },
        'sections': [{
          'widgets': [
            { 'textParagraph': { 'text': `<b>Error:</b> ${errorMessage}` } },
            { 'buttonList': { 'buttons': [{ 'text': 'Open Sheet', 'onClick': { 'openLink': { 'url': sheetUrl } } }] } }
          ]
        }]
      }
    }]
  };

  try {
    UrlFetchApp.fetch(GOOGLE_CHAT_WEBHOOK_LINK, {
      method: 'POST',
      contentType: 'application/json',
      payload: JSON.stringify(card)
    });
  } catch (e) {
    Logger.log(`Failed to send Chat notification: ${e.message}`);
  }
}
